### PR TITLE
Tweaks random map return and ice wall floor types.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
- Adds ice floor to exterior walls.
- Fixes issues with random maps not returning the result of turf changes.

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
Client view and skybox are screwed, DNM.

**Comment by QuakeIV** [comment]
github is pretty ass so there doesn't seem to be a proper way to message you directly

are you the guy that did some work on making unique biology for unathi in the old baystation codebase years ago? if so i was curious if any if that still exists and if i could look at it for my own purposes.  thanks for any info and sorry for not finding a better way to get in touch with you.

**Comment by MistakeNot4892** [comment]
I don't think that was me sorry, I never did any work on Unathi species code that I can recall.

Generally Discord is the best place to find people these days, Neb's is linked on the frontpage and has a bunch of crusty old coders who might know where the code is.

**Comment by QuakeIV** [comment]
Ill give it a poke

**Comment by MistakeNot4892** [comment]
Splitting this out into smaller PRs.

**Comment by MistakeNot4892** [comment]
Split complete.

**Review by afterthought2 — APPROVED** [review]

**Pull request merged**
