### PR TITLE
Move Ninja antagonist and gamemode into a modpack

### PR DESCRIPTION
**Pull request by out-of-phaze**
## Description of changes
Moves the Ninja special role and gamemode into a modpack.
Makes unnamed pAIs use the AI namelist instead of the ninja namelist.

## Why and what will this PR improve
Part of a project to move gamemodes into modpacks to avoid repeats of the Load-Bearing Deity Code incident of 2019 (three dead, 27 injured)

### CODE REVIEW

**Review by MistakeNot4892 — CHANGES_REQUESTED** [review]
Per Discord, I would like antags with a runtime-loaded map to be included in away_site_testing.

**Comment by out-of-phaze** [comment]
> Per Discord, I would like antags with a runtime-loaded map to be included in away_site_testing.

fwiw the map is already loaded on all maps that include the modpack, but I can do that, sure

**Review by MistakeNot4892 — DISMISSED** [review]
Per Discord this is tested without being included in away_sites.

**Comment by out-of-phaze** [comment]
> Per Discord this is tested without being included in away_sites.

to be more precise, `/decl/special_role/validate` loads it

**Review by MistakeNot4892 — APPROVED** [review]

**Pull request merged**
