### PR TITLE
Fixes click catcher coverage.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
## Description of changes
Extends click catchers to cover the entire possible view.

## Why and what will this PR improve
Currently on widescreen click catchers do not cover the left side of the screen.

## Authorship
Myself.

## Changelog
Nothing player-facing.

### CODE REVIEW

**Review by afterthought2 — DISMISSED** [review]

**Comment by MistakeNot4892** [comment]
Click catchers are behaving very oddly with regards to mapping to the appropriate turf, but this does extend coverage to the entire screen at least.

**Comment by afterthought2** [comment]
Probably need to check the client's actual view size when reading clicks, as e.g. the top-right 0, 0 click catcher will be on different turfs for different clients with different views. Alternatively, offset them from screen center instead of from top right.

**Comment by MistakeNot4892** [comment]
Didn't end up doing much with screen loc, but this PR is now working and responds to rescaling windows.

**Review by afterthought2 — APPROVED** [review]
Concept seems fine. Whether or not this makes off-by-one errors in some configurations, no idea, but hey.

**Pull request merged**
