### PR TITLE
Resets player view after exiting overmap interface

### PR DESCRIPTION
**Pull request by kelgaras**
## Description of changes

Bug fix
## Why and what will this PR improve

Bug fix is good
## Authorship

Spookerton
## Changelog

:cl:
bugfix: Fix bug where player's viewport offsets after exiting overmap interface
/:cl:

### CODE REVIEW

**Comment by afterthought2** [comment]
Can't do it like that, at least not here. Do it in the mob-level proc (if this is actually an issue on neb; I wasn't aware it was?)

**Comment by quardbreak** [comment]
Screen shaking/jitter issue is common here and your fix don't handle specific view cases. Here is my fix which also unlocks overmap wide-screen: https://github.com/NebulaSS13/Nebula/commit/730ced2414b78975911769ef6a4eef5402796f38

**Comment by kelgaras** [comment]
> Screen shaking/jitter issue is common here and your fix don't handle specific view cases. Here is my fix which also unlocks overmap wide-screen: [730ced2](https://github.com/NebulaSS13/Nebula/commit/730ced2414b78975911769ef6a4eef5402796f38)

If you're going to finish that PR, then I close this one, and I leave it to you.

**Comment by kelgaras** [comment]
> Can't do it like that, at least not here. Do it in the mob-level proc (if this is actually an issue on neb; I wasn't aware it was?)

On heistia already stella nova this error exists, and there is. In any case, I'll try using the qb code

**Pull request closed without merging**
