### PR TITLE
Porting obfuscated medication from Europa.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
image

🆑 
add: When the bigpharma pack is ticked, pre-packaged medication (bottles, pills, syringes) that is not inside a first aid kit or emergency pouch will generate a random brand name and only tell you the actual reagent if you have a level or two in Chemistry.
/🆑

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
Guess we need to have a conversation about Unicode again.
@Lohikar 
@afterthought2
@eckff

**Comment by Lohikar** [comment]
Issue with Unicode was resolved by another PR (per discord discussion), rebase and this should be good.

**Comment by comma** [comment]
skill threshold seems a bit steep, especially considering it's chemistry only.
I'd suggest keeping it at Basic, and maybe letting either Chemistry or Medicine be checked.

**Comment by MistakeNot4892** [comment]
Done.

**Review by comma — APPROVED** [review]

**Pull request merged**
