### PR TITLE
new sprites for vents and scrubbers

### PR DESCRIPTION
**Pull request by kelgaras**
## Description of changes
icons of vents and scrubbers changed to new
dreamseeker_30WBBLPkR9
dreamseeker_hbKU1qP18B

## Why and what will this PR improve
looks pretty good
## Authorship
@Keekenox
## Changelog
:cl:
rscadd: new icons for vents and scrubbers
/:cl:

### CODE REVIEW

**Review by afterthought2 — CHANGES_REQUESTED** [review]
These lack build states. Also need to track down the source.

**Comment by MistakeNot4892** [comment]
If you could split the fix out into its own PR targeting stable, that can go in fine by itself.

**Comment by MistakeNot4892** [comment]
Vote was heavily in favour. If you can supply build states and find a source this can be merged.

**Comment by kelgaras** [comment]
> Vote was heavily in favour. If you can supply build states and find a source this can be merged.

I finished the missing sprites and found the original [source](https://github.com/Baystation12/Baystation12/pull/28123)

**Review by MistakeNot4892 — APPROVED** [review]

**Review by afterthought2 — APPROVED** [review]

**Pull request merged**
