### PR TITLE
Taj resprite. [IDB IGNORE]

### PR DESCRIPTION
**Pull request by MistakeNot4892**
## Description of changes
New, better cat icon by Azlan. Left is current, right is new:
image

## Why and what will this PR improve
catte

## Authorship
Azlan for the touched up sprite, myself for conversion/code/accessory and markings.

## Changelog
:cl:
tweak: Tajaran icon has been updated with new work from Azlan.
/:cl:

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
Will update with screenshots when it's closer to working, opening this primarily for the diff.

**Comment by MistakeNot4892** [comment]
Markings need refinement and I'm not competent enough to re-animate the tail states for the swishes, but this is good to go imo.

**Comment by MistakeNot4892** [comment]
TODO: tail animation states.

**Review by afterthought2 — DISMISSED** [review]

**Comment by MistakeNot4892** [comment]
Yeah I am not reanimating these tail states. Cats can have static tails until someone else does it rip.

**Comment by MistakeNot4892** [comment]
Ended up resampling the old tail icons to the new palette, they line up fine, so animations are still in. This is ready to go.

**Review by afterthought2 — APPROVED** [review]

**Pull request merged**
