### PR TITLE
Renamed health on hydro tray to plant_health

### PR DESCRIPTION
**Pull request by PsyCommando**
## Description of changes
Hydro trays having a var called "health" for holding the plant health would cause name collision in my obj damage handling PR. So I renamed it to plant_health here instead.

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
Please target staging with fixes. Dev is going to be sitting there for the next six months.

**Review by MistakeNot4892 — APPROVED** [review]

**Comment by PsyCommando** [comment]
That's not a fix. Its something I need for another PR to avoid name collision.

**Comment by MistakeNot4892** [comment]
Misunderstood this as being something from the item damage PR, my mistake.

**Comment by PsyCommando** [comment]
> Misunderstood this as being something from the item damage PR, my mistake.

Well, it's part of it. I renamed the health var on hydro trays so they don't collide with the health var of objects. 
It's just not very useful to me if it goes to staging or stable :P

**Comment by MistakeNot4892** [comment]
If it goes to staging or stable it also goes to dev so I'm not sure what you're suggesting.

**Comment by PsyCommando** [comment]
Just nvm. XD
It's not a fix, so dev is ok?

**Comment by MistakeNot4892** [comment]
Yep.

**Pull request merged**
