### PR TITLE
Moving painted color behavior to /obj/item and /obj/structure.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
## Description of changes
- Unifies some paint color handling from windows and wall frames on structure.
- Adds paint color handling to items.
- Updates gear tweak to use color setters.

## Why and what will this PR improve
Should allow materials to be painted without materials overriding the color.
More consistent code.

## Authorship
Myself.

## Changelog
Nothing player-facing.

### CODE REVIEW

**Review by comma — DISMISSED** [review]

**Review by out-of-phaze — APPROVED** [review]

**Review by out-of-phaze — CHANGES_REQUESTED** [review]
I don't know why, but this seems to have broken SSatoms...?

**Comment by MistakeNot4892** [comment]
No idea why this is breaking SSatoms.

**Comment by out-of-phaze** [comment]
From conversation on Discord: `/obj/item/light/set_color()` calls `update_icon()` calls `set_color()` etc.

**Review by out-of-phaze — DISMISSED** [review]

**Comment by MistakeNot4892** [comment]
Structures are trying to update icon before materials have initialized. :(

**Review by out-of-phaze — DISMISSED** [review]

**Review by out-of-phaze — APPROVED** [review]
Been waiting on conflicts for two days, so it's past the 24 hour approval time.

**Pull request merged**
