### PR TITLE
Repaths simple_animal to critter.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
This is a find and replace job, should be identical in function. Reasoning:
- `simple` is a lie.
- `animal` is a lie.

Amendment to above: second commit does change logic, but it is all editing var names/proc names/comments.

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
local man fucks up find and replace

**Comment by MistakeNot4892** [comment]
Compiles, runs, went through and checked all the changes and I don't appear to have broken anything.

**Review by comma — DISMISSED** [review]

**Review by comma — DISMISSED** [review]

**Comment by MistakeNot4892** [comment]
Map diffs are constantly failing on this PR and I'm not clear on why.

**Comment by MistakeNot4892** [comment]
This evidently isn't getting merged.

**Pull request closed without merging**
