### PR TITLE
Porting LemonInTheDark's roundstart subsystem optimizations.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
## Description of changes
Optimizes the delay offset on subsystems during runlevel change to account for a large number of subsystems causing a long delay. Full details in the original PR body: https://github.com/tgstation/tgstation/pull/71730

## Why and what will this PR improve
Removes the lengthy delay at roundstart, rounds start almost immediately now.

## Authorship
@LemonInTheDark for the code I stole (with many thanks).
@Kapu1178 for pointing out the optimization.

## Changelog
Nothing player-facing.

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
@LemonInTheDark You may be tickled to know this has finally made a year and a half old CI fail happen consistently, so thank you.

**Comment by LemonInTheDark** [comment]
lmao

**Review by comma — DISMISSED** [review]

**Comment by out-of-phaze** [comment]
Notably: Looks like the CI fail is caused by using pumps that start on; I got it in the Unishi engine room locally, and confirmed that the Desperado pumps with the IDs listed are also the `/on` subtype.

**Comment by out-of-phaze** [comment]
> Notably: Looks like the CI fail is caused by using pumps that start on; I got it in the Unishi engine room locally, and confirmed that the Desperado pumps with the IDs listed are also the `/on` subtype.

It's the timer subsystem not finishing a full run in one cycle.

**Review by comma — APPROVED** [review]

**Comment by MistakeNot4892** [comment]
This appears to be passing, IDB is hung up on it for some reason (probably due to accidentally rebasing it to dev earlier).

**Comment by MistakeNot4892** [comment]
Going ahead and merging this so I can get the branches into sync.

**Pull request merged**
