### PR TITLE
Refactoring ex_act() procs.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
- Refactors `ex_act()` into `explosion_act()` which attempts to preserve a call chain all the way to `/atom`.
- Moves reagent explosions down to `/atom`.
- Moves `/obj/structure/destroyed()` to `/atom/physically_destroyed()`.
- Moves several `dump_contents()` procs to `/atom/dump_contents()` and calls it in physical destruction.
- Generalizes propagation of explosions to contents using an `/atom/get_contained_external_atoms()` proc.

Not tested yet. This was meant to be a small PR.

I have concerns that `get_contained_external_atoms()` is going to need overrides for `/obj/machinery` and anything with contents-held atoms that shouldn't be interacted with (similar to how humans previously farted out all their organs when Drop Everything was used).

### CODE REVIEW

**Review by afterthought2 — DISMISSED** [review]

**Comment by MistakeNot4892** [comment]
This still causes or exposes a bad runtime problem with proxy triggers.

**Review by deathride58 — DISMISSED** [review]

**Comment by deathride58** [comment]
Probably would be worth doing some further investigations on whatever's causing those runtimes. There's nothing in this PR that really touches proximity triggers (as far as I can tell at a glance, at least), so I'm leaving my approval for now, since it seems the issue may lie elsewhere. Having more eyes on this PR would probably be a very good idea, though.

**Review by afterthought2 — DISMISSED** [review]
Fuck it. Can deal with proximity triggers separately.

**Review by afterthought2 — DISMISSED** [review]
Well, proximity trigger updates are in. If there are proximity trigger issues caused by this, can open an issue and address from there.

**Review by afterthought2 — APPROVED** [review]

**Pull request merged**
