### PR TITLE
Killing the dd sort procs.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
WIP, need to reimplement a sorted insertion proc. Opening for CI/diff.

## Description of changes
- Kills the old `dd_` prefix sort procs, uses `sortTim` instead.
- Renames `sortTim()` to `sort_list()`.
- Adds `insert_sorted()`

## Why and what will this PR improve
Removes redundant/inefficient system, makes sortTim named less weird.

## Authorship
Myself.

## Changelog
Nothing player-facing.

### CODE REVIEW

**Comment by Lohikar** [comment]
Not a fan of renaming TimSort, that's going to be a point of confusion.

**Comment by MistakeNot4892** [comment]
As you indicated, the name makes sense, I'll revert the rename.

**Comment by Kapu1178** [comment]
What did my man Tim do to you?!

**Comment by MistakeNot4892** [comment]
He never sends me a birthday card :(

**Pull request closed without merging**
