### PR TITLE
Add shuttle rotation support

### PR DESCRIPTION
**Pull request by out-of-phaze**
## Description of changes
Shuttles can now rotate when landing, in order to align their landmark with their landing site's landmark. This is optional and controlled by the destination landmark.

TODO:
- [x] Add HUD button for rotating 90/-90 degrees during manual landing.

## Why and what will this PR improve
Shuttle rotation's cool.

### CODE REVIEW

**Comment by out-of-phaze** [comment]
So, one issue: this kind of sucks. I need to make the shuttle landmark once again just the center of mass of the shuttle, used for rotation, and then have separate landmarks for docking points like airlocks. That's gonna be a bit of a pain, probably... open to any advice/help.

**Comment by out-of-phaze** [comment]
This current implementation causes issues with planetary landing because there's no ability to land with the landmark at the center of the ship. I need to find a good way to fix this before it can be merged.

**Comment by out-of-phaze** [comment]
I have fixed it and a bunch of long-standing issues with docking/etc., plus some new ones introduced by the 515 migration. Fuck yes.
TODO before I'll mark it ready for review:
- [x] Fix windows, lattices, low walls, etc. not updating icons properly
  - [x] Fix window icons/connections
  - [x] Fix lattice icons/connections
  - [x] Fix low wall icons/connections
- [x] Fix doors not setting direction properly
- [x] Fix selecting 'none' for center of rotation
- [x] Add ability for centers of rotation to set `shuttle_docking_controller`
- [x] Fix rotation direction/reorientation calculations

**Comment by out-of-phaze** [comment]
Could still use feedback on UX stuff, but honestly that can be changed on dev/staging/etc. Holy shit, it's finally ready.

**Review by MistakeNot4892 — APPROVED** [review]

**Comment by MistakeNot4892** [comment]
#yolo

**Pull request merged**
