### PR TITLE
Adding SSpathfinding.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
## Description of changes
- Adding a subsystem to handle scheduling/tick checking of A* pathfinding.
- Converts ~~bots and~~ ICs to use the subsystem.
- Adds handling for paths to mob automove.

## TODO

- [X] Coarse implementation.
- ~~Get bots to actually work again.~~
- ~~Test cleanbot.~~
- ~~Test farmbot.~~
- ~~Test medibot.~~
- ~~Test secbot.~~
- ~~Test floorbot.~~
- ~~Test mulebot.~~
- [x] Get path following, updating and invalidation working on a test mob controller type.
- [x] Test asynchronous/tick checked AStar().

## Why and what will this PR improve
- Allows use of A* without locking up the entire game.
- Generalizes pathfinding off the bot subtype so mob controllers in general can use it.

## Authorship
Myself.

## Changelog
Nothing player-facing.

### CODE REVIEW

**Comment by PsyCommando** [comment]
I don't know if it's in the plans down the road, but having some way to prioritize some movers above others would be great. Since, having a lot of idle mobs running their idle or like fluff pathfinding over mobs in active combat would probably be a bit problematic. 

Like say, if there's 12 cleaner and farm bots bots trying to get a path and then there's 2 medbots trying to path to heal people, and 2 hostile mobs trying to path to attack players, you probably don't care much about the cleaner and farm bots pathing really long paths over those that need to react quickly?

**Comment by MistakeNot4892** [comment]
I am not planning on adding pathfinding priority in this PR. I just want it subsystemised and tickchecked, if someone wants to implement scheduling down the track then they can, but I am not adding more scope to this PR, I am already struggling to get through it.

**Comment by MistakeNot4892** [comment]
Splitting the bot aspect out of this for a separate PR.

**Comment by MistakeNot4892** [comment]
Need to remove or integrate/test the asynchronous A* for bot code.

**Comment by MistakeNot4892** [comment]
This has broken bot behavior, but I can't tell if it was my changes or if bots were already screwed. Need to test bots on clean dev I guess.

**Comment by noelle-lavenza** [comment]
works perfectly with #4586 in.

**Comment by MistakeNot4892** [comment]
Farmbots and cleanbots are now working fine.

**Comment by MistakeNot4892** [comment]
Some mob AI issues to work through with this one.

**Comment by MistakeNot4892** [comment]
Fixed base automove and target validation.

**Review by out-of-phaze — APPROVED** [review]

**Pull request merged**
