### PR TITLE
Make planetary atmos scans allow atmos skill

### PR DESCRIPTION
**Pull request by SierraKomodo**
:cl:
tweak: Atmospheric readings when scanning planetoids is now reliant on atmospherics or science skill instead of only science skill (You only need one of the two).
/:cl:

### CODE REVIEW

**Review by MistakeNot4892 — DISMISSED** [review]
Seems weird to make Atmospherics a required skill for pilots but shrug.

**Comment by comma** [comment]
I think it's super non-obvious that for piloting/sciencing you need an engineering atmos skill, and that skill in general should just die off TBH.
It's grandfathered form before mechanical skills and is used in literally 1 place.

**Comment by MistakeNot4892** [comment]
Relating to convo on Discord about the skill - https://github.com/NebulaSS13/Nebula/pull/490

**Comment by Techhead0** [comment]
If the skill isn't being removed, another option is making it science *or* atmos skill here

**Comment by SierraKomodo** [comment]
Updated to be science OR atmos, as recommended by @Techhead0

**Review by MistakeNot4892 — APPROVED** [review]
Compromise works for me.

**Pull request merged**
