### PR TITLE
Cash and vending machine refactor.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
- Cash appearance is now defined per map.
- Currencies are defined as `/decl/currency` and are at least nominally supported by mechanics.
- Cash in general has been refactored to be less internally bizarre. No more `/bundle`.
- New cash colours are based on the Australian banknote spectrum, no I will not change this.
- Charge cards are now their own object type.
- Material coins now have an associated currency and value (but aren't legal tender except to traders).
- Vendor prices are now generated from item worth using a new repository, which also holds matter info.

### CODE REVIEW

**Review by comma — DISMISSED** [review]

**Comment by MistakeNot4892** [comment]
Seems to work ok now.

**Comment by MistakeNot4892** [comment]
This is spiralling out of control. Will try not to add more shit.

**Comment by MistakeNot4892** [comment]
Should be all good. I probably missed a few vendors that shouldn't have prices, but that can be fixed as people report them.

**Comment by MistakeNot4892** [comment]
Ok properly done now.

image

**Comment by MistakeNot4892** [comment]
Ok ok properly done for real.
image

**Comment by Techhead0** [comment]
Pretty sure /obj/machinery/vending/hydronutrients and /obj/machinery/vending/hydroseeds were free before, but if the change is intentional then go ahead

**Review by comma — APPROVED** [review]

**Pull request merged**
