### PR TITLE
Attack_hand and buckling refactor.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
## Description of changes

Split off from #2031.
Moves buckling down to `/atom/movable`.

## Why and what will this PR improve
Preliminary work for ridable mobs, essentially.

## Authorship
Myself.

## Changelog
Nothing player facing.

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
Depends on #2037 to work properly, DNM till that's in and I can rebase/update.

**Comment by MistakeNot4892** [comment]
Trying to get fucking cow tipping of all things to work.

**Comment by MistakeNot4892** [comment]
Depends on #2131.

**Comment by MistakeNot4892** [comment]
- Janicart offsets are not working.
- Wheelchairs are immobile.
- Beds and chairs are working.

**Comment by MistakeNot4892** [comment]
Depends on #2140.

**Comment by MistakeNot4892** [comment]
Janicart offsets are not working.
    Wheelchairs are immobile.
    Beds and chairs are working.

**Review by afterthought2 — APPROVED** [review]

**Pull request merged**
