### PR TITLE
Updates pull request template to tgstation and TauCeti version

### PR DESCRIPTION
**Pull request by quardbreak**
## Description of changes

Changes Nebula's PR template to tgstation and TauCeti version.

## Why and what will this PR improve

Adds authorship section and section where people *should* explain which changes they do and why.
It allow reviewers and maintainers easier to know with what they deal.

## Authorship

TauCetiStation, https://github.com/TauCetiStation/TauCetiClassic/blob/master/.github/PULL_REQUEST_TEMPLATE.md
tgstation, https://github.com/tgstation/tgstation/blob/master/.github/PULL_REQUEST_TEMPLATE.md

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
This will need some discussion from maints but I think it's fine personally.

**Comment by afterthought2** [comment]
On the one hand, I think these templates are childish (you should just describe your PR succinctly in the header). On the other hand, I have noticed an uptick in the number of PRs with no header at all or unhelpful stuff in the header, so maybe we need something like this.

**Comment by Kurgis** [comment]
As more beginning contributors are entering the downstreams and introduced here, this PR template will become more useful. I agree it really wasn't needed _before_, but that may change.

**Review by MistakeNot4892 — APPROVED** [review]
I don't think it harms anything to have it in place.

**Pull request merged**
