### PR TITLE
 drinks are now not that expensive

### LINKED ISSUE #894: Drink Machines prohibitively expensive
#### Description of issue
Drink Machines cost a great deal more than you would expect

#### Difference between expected and actual behavior
most employees on the ship should probably be able to afford more than just a single dirnk

#### Steps to reproduce
approach robust softdrinks vender.  prepare yourself for the ultimate in fizzy drinks experiences, followed rapidly by disappointment and unquenched thirst

#### Specific information for locating

/obj/machinery/vending/cola
--

#### Length of time in which bug has been known to occur

since forever

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: fa5f5a3a9c8e0f7f9e8f145bc0c70b46c6bf41ba - dev - 2020-09-12
Game ID: b88-akEb
Current map: Tradeship Ivenmoth

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

### PR DESCRIPTION
**Pull request by kiVts**
Every hot drink food in vendomat price was reduced by five or ten
Fixes #894 

Not fixes though but  anyway

-tweak: drinks now cheaper

### CODE REVIEW

**Comment by kiVts** [comment]
If someone would link this pr to issue I would give a pleasure

**Comment by kiVts** [comment]
https://github.com/NebulaSS13/Nebula/issues/894#issue-700450418

**Review by comma — APPROVED** [review]

**Comment by MistakeNot4892** [comment]
Aren't those numbers quanitity rather than cost? Cost is generated at runtime.

**Comment by comma** [comment]
Actually now that you mention that yeah we did move to dynamic generation didn't we

**Comment by kiVts** [comment]
Ufffff

**Comment by MistakeNot4892** [comment]
Going to go ahead and close this one since it's a month old, for reference changing the prices of drinks will need you to change the `value` var on the material stored in the cans.

**Pull request closed without merging**
