### PR TITLE
Ports SSprofiler from Paradise Station

### PR DESCRIPTION
**Pull request by quardbreak**
Ports SS220 (Actually, Paradise one) SSprofiler, provided by @Vallat.
This thing allows to collect profiler's data in JSON format as log entry.

~~Currently don't respect config option because I don't know how to integrate the check in subsystem. This is main reason why I putting it on draft.~~

### CODE REVIEW

**Comment by Lohikar** [comment]
I don't really see what the utility of this is.

**Comment by afterthought2** [comment]
Might be better for downstream use if performance or debugging is a particular downstream concern. It's completely modular, so will be easy to add there. On the other hand, we probably don't have much use for it upstream, and we definitely don't want to recommend/encourage downstreams to use it in general (it has some performance impact, requires expertise to use the collected data, produces a lot of log volume, etc.)

If others feel like this is useful upstream, then that changes things. @MistakeNot4892, I guess, as you do most of the testing. Can also check in with Outreach.

**Comment by quardbreak** [comment]
I don't think it's modular. It requires make defines and update it every time when someone adds new subsystem define. Also, it uses config, which is not modular.

**Comment by MistakeNot4892** [comment]
I would not personally get much use out of this for testing. The inbuilt profiler is fine for what I've needed to profile in the past. The sendmaps stuff might be useful but I'm ambivalent about the rest.

**Comment by MistakeNot4892** [comment]
Maint vote was not in favour and the argument for adding it wasn't compelling/relevant to our general usage.

**Pull request closed without merging**
