### PR TITLE
Added SM to ministation, also fixed TEG sprite [MDB IGNORE]

### PR DESCRIPTION
**Pull request by gyurka66**
## Description of changes
Removed 2 of the 3 solars on Ministation and replaced them with a Supermatter crystal and a single TEG connected to it. Since the sprite of the TEG was broken due to it missing the icon variable i fixed it. The SM has an ejection system. The first engineering room will now serve as an SM monitoring room. Blast shields were added to all internal engineering windows. Two radiation closets were added. The southern side of engineering received new floors, more in line with how SM rooms usually look on other maps.

## Why and what will this PR improve
Solars are too simple to provide fun for engineers in my opinion. An SM engine provides much more interesting gameplay.

## Authorship
Gyurka66

## Changelog

:cl:
bugfix: Fixed the TEG icon
maptweak: Added SM to engineering
maptweak: Removed 2 of 3 solars
/:cl:

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
Could you possibly split the generator icon out into a separate commit and point it at staging? 
EDIT: Disregard: https://github.com/NebulaSS13/Nebula/pull/2465#pullrequestreview-989924889

**Comment by MistakeNot4892** [comment]
For reference:
https://cdn.discordapp.com/attachments/810767449904644146/980755473554882620/unknown.png

**Comment by gyurka66** [comment]
how it currently looks 
kép

**Review by MistakeNot4892 — DISMISSED** [review]

**Comment by MistakeNot4892** [comment]
Gen fix will conflict but it's an easy resolve

**Comment by gyurka66** [comment]
wth did i just do?

**Review by MistakeNot4892 — APPROVED** [review]
Looks like you resolved a conflict and pushing the changes dismissed my review, nothing to worry about.

**Pull request merged**
