### PR TITLE
Micro-optimizes get_decl() for materials.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
`/repository/decls` will pre-fetch the entire `/decl/material` tree in `New()`, which allows materials to be fetched with a simple macro. Given how often get_decl() is used for materials I think this should be worthwhile even if it's a bit more brittle.

### CODE REVIEW

**Comment by Andrew-Fall** [comment]
Why not GET_DECL_FAST? Easier to say

**Comment by MistakeNot4892** [comment]
I didn't close this PR. Github why.

**Comment by Techhead0** [comment]
Github autocloses PRs w/ 0 line changes, I guess you may have force-pushed the wrong commit

**Comment by MistakeNot4892** [comment]
Yeah I reset to origin on autopilot I think.

**Comment by MistakeNot4892** [comment]
For reference, months later, the `GET_DECL` macro removed the benefit/need for this optimization, hence it was never reopened.

**Pull request closed without merging**
