### PR TITLE
Turret Rewrite

### PR DESCRIPTION
**Pull request by SierraKomodo**
Refactoring turrets by rewriting them entirely.

Planned updates include:
 - New effects for emagged, EMP'd, and malf upgraded turrets (Including a 'haywire' mode where the turrets go crazy and start firing off randomly)
 - Turrets use the same projectile as the gun used to create them (Ion turrets anyone?)
 - Turrets have the same firemode options as the gun used to create them
 - Turrets have a new control panel UI
 - Turrets have a wiring panel that can be manually hacked
 - Turrets can be constructed, deconstructed, and repaired
 - Turret frames can be built from differing materials that affect turret health

### CODE REVIEW

**Comment by CrimsonShrike** [comment]
Perhaps could use the new machine components to decide how they are controlled. Remote input component links them to a control panel, regular input and screen allow a single turret to be modified on the go?

**Comment by SierraKomodo** [comment]
> Perhaps could use the new machine components to decide how they are controlled. Remote input component links them to a control panel, regular input and screen allow a single turret to be modified on the go?

Can you direct me toward a object/file that uses these? I work best off existing examples.

**Comment by SierraKomodo** [comment]
Added a weapon_control_system stock part to serve as the link between turret and inserted gun.

**Comment by SierraKomodo** [comment]
Burst fire mode for energy weapons now works.

**Comment by SierraKomodo** [comment]
Wire datum WIP. Power and haywire wires done.

**Comment by MistakeNot4892** [comment]
This has not been touched for a month and you didn't respond on Discord, so going to close it for the time being. Feel free to reopen when you revisit the PR.

**Pull request closed without merging**
