### PR TITLE
Blast doors now autoset direction from neighbors.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
Implements #132, firedoors already do this.
Airlocks will also now respect set_dir_on_update.

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
Noting that they are still going to look weird on tradeship due to mapping and smoothing lists.

image

Work fine if left to their own devices.

**Review by comma — APPROVED** [review]

**Comment by afterthought2** [comment]
I don't actually buy they should be doing this in `update_icon` at all. I think they should do this in `Initialize`.

**Comment by MistakeNot4892** [comment]
They need to be able to update when connections change.

**Comment by afterthought2** [comment]
I'm not sure that's true; they should likely not be changing dir just because their neighbors changed. But even if that's the case, it should be done in the connections update proc, which is separate from `update_icon`.

**Comment by MistakeNot4892** [comment]
Well, I'm unwilling to touch or refactor any connection or direction setting code and this change is consistent with the other door types.

**Pull request merged**
