### PR TITLE
chemdart properly init its reagents

### PR DESCRIPTION
**Pull request by PsyCommando**
## Description of changes
Seems like it was happening too late, so I moved it to initialize_reagents.

### CODE REVIEW

**Review by MistakeNot4892 — DISMISSED** [review]
Can this target stable or staging?

**Comment by PsyCommando** [comment]
I thought we didn't target stable with the freeze?

**Comment by MistakeNot4892** [comment]
Why wouldn't we?

**Comment by PsyCommando** [comment]
I dunno. I just remember that coming up at one point.

**Comment by MistakeNot4892** [comment]
The purpose of staging is to prevent new dev PRs introducing regressions and instabilities while staging is being tested and verified for merge to stable. Anything that can target stable (fixes, etc), should target stable, otherwise they should target dev unless they are a fix for something on staging that isn't on stable.

**Comment by PsyCommando** [comment]
Moved to staging!

**Review by MistakeNot4892 — APPROVED** [review]

**Pull request merged**
