### PR TITLE
Excepts simple_animals from weather effects.

### LINKED ISSUE #4153: Wildlife on Shaded Hills die of hail
#### Description of issue
Hail kills all the wildlife.

#### Difference between expected and actual behavior
Hail should not kill all the wildlife. Either they should be immune, or they should run for cover.

#### Steps to reproduce
1. Cover yourself in oil.
2. Wait for it to hail.
3. Ow ow ow ow ow
4. All the animals are dead.

#### Specific information for locating
N/A

#### Length of time in which bug has been known to occur
Since wildlife and weather both coexisted on this map.

#### Client version, Server revision & Game ID
Latest dev.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

### PR DESCRIPTION
**Pull request by MistakeNot4892**
Should fix #4153

### CODE REVIEW

**Review by out-of-phaze — APPROVED** [review]
contact reagent dripping seems undocumented but i'm not opposed

**Comment by MistakeNot4892** [comment]
Undocumented how? I just moved the logic.

**Review by out-of-phaze — CHANGES_REQUESTED** [review]
> Undocumented how? I just moved the logic.

it's only in the added part of the diff, so i can't tell where it was moved from. did you not remove the old copy or something?

oh lol this pr targets stable but the code you're moving is only on dev. think this should get retargeted to dev then

**Comment by MistakeNot4892** [comment]
Oh whoops.

**Comment by MistakeNot4892** [comment]
I wanted this fix to go to stable, but I've commented out the contact reagent stuff - will make it easier to resolve when I pull the commit into dev.

**Review by out-of-phaze — APPROVED** [review]

**Pull request merged**
