### PR TITLE
Remove ID card payment

### PR DESCRIPTION
**Pull request by biscuitWizard**
Converted vending machine and laptop vendor to only accept charge_cards in prep for https://github.com/NebulaSS13/Nebula/pull/543

### CODE REVIEW

**Comment by biscuitWizard** [comment]
Blocked by #543

**Comment by comma** [comment]
What for? Sounds like adding pain in the ass for sake of it.
Now instead of just being able to buy some smokes after joining you have to go hunt down an ATM, get a credstick, and then finally be able to.

**Comment by MistakeNot4892** [comment]
I would be in favour of this due to the decoupling of local access and bank account, so long as the on-join proc dumped half or two thirds of your money onto a credstick rather than into your account, for the usability concern @comma mentioned above. Could possibly be a toggle in chargen (`Money on hand: none [some] all`).

**Comment by comma** [comment]
On-join spawn of credstick in your PDA would solve my ree yea.

**Comment by biscuitWizard** [comment]
loadout prefs for credstick has been added.

**Review by comma — APPROVED** [review]

**Pull request merged**
