### PR TITLE
Fix bad limb max damage scaling

### PR DESCRIPTION
**Pull request by PsyCommando**
## Description of changes
Fix the problem with limbs getting inconsistent damage values depending on how they were created. 
Turns out the values were scaled down on each call of set_species.
Also fix neo-avian no spawning with any languages when created in-game or when changing a mob's species.

I dunno if it'll be useful since loaf has been fixing it too. But here it is in any cases.

## Changelog

:cl:
bugfix: Fix incoherent max damage scaling on human mob limbs. Also fix things depending on it.
/:cl:

### CODE REVIEW

**Review by MistakeNot4892 — APPROVED** [review]

**Comment by MistakeNot4892** [comment]
Oops, fixes need to target staging. Could you rebase?

**Comment by MistakeNot4892** [comment]
I had to pull your commits into staging for my PR so if you'd prefer we can just merge them with that one rather than rebasing here.

**Comment by PsyCommando** [comment]
> I had to pull your commits into staging for my PR so if you'd prefer we can just merge them with that one rather than rebasing here.

Sure, you can just merge!

**Comment by MistakeNot4892** [comment]
Alrighty cheers.

**Pull request closed without merging**
