### PR TITLE
Fix slurred speech.

### PR DESCRIPTION
**Pull request by noelle-lavenza**
## Description of changes

BYOND doesn't use `break` to exit switches. Oops. My bad.
## Why and what will this PR improve

Before, it would only get a few characters in before stopping prematurely.
## Authorship
Me for the bug and me for the fix.

## Changelog

:cl: Noelle Lavenza
bugfix: Slurred speech now works again.
/:cl:

### CODE REVIEW

**Review by MistakeNot4892 — APPROVED** [review]
Why the comments?

**Comment by noelle-lavenza** [comment]
> Why the comments?

I, uh, I'm not sure. I think it was just to make it explicit that 9 to 14 did nothing? Since the ranges used here are kind of weird; it alternates odd-even for no good reason.

The other comments were already present.

**Comment by Gaxeer** [comment]
> > Why the comments?
> 
> I, uh, I'm not sure. I think it was just to make it explicit that 9 to 14 did nothing? Since the ranges used here are kind of weird; it alternates odd-even for no good reason.
> 
> The other comments were already present.

You've got `else` in switch/case

**Comment by MistakeNot4892** [comment]
`else` in a switch is valid in DM.

**Comment by Gaxeer** [comment]
> `else` in a switch is valid in DM.

I mean, it's possible to replace this `if (9 to 14)` with `else`

**Comment by Gaxeer** [comment]
> `else` in a switch is valid in DM.

I am blind. I thought Jade `add` if (9 to 14)

**Pull request merged**
