### PR TITLE
Markings UX improvements.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
## Description of changes
- Adds left and right arrows to facial hair and head hair selection, which iterate up and down the hair list.
- Adds up and down buttons to markings to allow easy reordering/layering changes.
- Standardizes marking and hair display formatting.

## Why and what will this PR improve
Looks nice, is less unpleasant to use.
image

## Authorship
Idea came from playing on Polaris but implementation is mine.

## Changelog
:cl:
tweak: You can now use arrow buttons to adjust markings and hair in character setup.
/:cl:

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
Unicode arrows that are filled in and thicker have been suggested but I cannot get them to work with DM/in HTML, any suggestions appreciated.

**Comment by PsiOmegaDelta** [comment]
Does the current version still have these peculiar height offsets?
image

**Comment by MistakeNot4892** [comment]
There's consistently some weird offsets like that with the link CSS, and they change between browser refreshes. :(

**Comment by MistakeNot4892** [comment]
Trying to get Unicode arrows to work completely broke the CSS for the links, so I'm calling this done for now. If someone with a bigger brain than me can put in filled arrows, please do.

**Review by out-of-phaze — APPROVED** [review]

**Pull request merged**
