### PR TITLE
Reworks fox and deer icons.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
Greyscales @PlayerDeer's fox icon and breaks the markings/socks/eyes out into overlays.

image

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
image

**Comment by MistakeNot4892** [comment]
Merged the deer icons into this and reworked the method a bit since Pyrelight testing showed they were busted.

**Comment by MistakeNot4892** [comment]
Issue with deer getting ghost icons when prone.

**Comment by MistakeNot4892** [comment]
Fixed.

**Review by out-of-phaze — APPROVED** [review]

**Pull request merged**
