### PR TITLE
Added per-type machinery dexterity requirements.

### LINKED ISSUE #794: DEXTERITY_SIMPLE_MACHINES issues
#### Description of issue
having a prosthetic arm with DEXTERITY_SIMPLE_MACHINES seems to be too restrictive

#### Difference between expected and actual behavior
a lightswitch would be a simple machine, you would think, yet, you cannot use a light switch with a DEXTERITY_SIMPLE_MACHINES prosthetic. the same applies to doors.

#### Steps to reproduce
have a prosthetic hand with DEXTERITY_SIMPLE_MACHINES
try to use a lightswitch or door

#### Client version, Server revision & Game ID

this was found on ScavStation's code

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

### PR DESCRIPTION
**Pull request by MistakeNot4892**
Fixes #794.

### CODE REVIEW

**Review by afterthought2 — DISMISSED** [review]
Ree, this isn't my fault.

**Comment by Greenjoe12345** [comment]
asked to post here as a reminder of things that would be under simple dexterity
vending machines
basic buttons
fire alarms
floor lights
floodlights
smartfridge
maybe space heater?
elevator controls?

**Comment by PsiOmegaDelta** [comment]
I blame afterthought2

**Review by PsiOmegaDelta — DISMISSED** [review]
Code as is looks fine, and if you do want to add additional machines do go ahead

**Review by afterthought2 — APPROVED** [review]

**Comment by MistakeNot4892** [comment]
This'll do it for this PR.

**Pull request merged**
