### PR TITLE
Airlock panel opens with wrench

### PR DESCRIPTION
**Pull request by SolatK**
## Description of changes

Airlock panel opens with wrench instead crowbar
## Why and what will this PR improve

to open the panel with a crowbar, the airlock had to be welded or boled. Wrench doesn't have this problem.
## Authorship

me
## Changelog

:cl:
tweak: Airlock components panel now opens with wrench
/:cl:

### CODE REVIEW

**Comment by afterthought2** [comment]
Need to also modify the mechanics text below.

The issue with this kind of interaction is that you can't do the reverse, closing the panel with a wrench, because that does something else.

**Comment by SolatK** [comment]
> The issue with this kind of interaction is that you can't do the reverse, closing the panel with a wrench, because that does

the components panel is closed with a screwdriver before my change and after

**Comment by SolatK** [comment]
> 



> Need to also modify the mechanics text below.

"You open the main cover panel on \the [machine], exposing the internals." to "You unwrench locking bolts and open the main cover panel on \the [machine], exposing the internals."?

**Comment by afterthought2** [comment]
No, there's a proc below, `mechanics_info`, which explains what tool to use for what.

**Review by comma — APPROVED** [review]
Sure, it was requiring welding etc just to mirror old deconstruction steps

**Pull request merged**
