### PR TITLE
Various Shaded Hills tweaks/fixes from testing.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
- Manually defines some subtypes as the macros need 515.
- Fixes eyes not overlaying after the first colour change.
- Fixes rocks not fitting in pockets.
- Fixes weirdness from burn products inserting `"type"` instead of `type` into the products list.

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
Going to cherrypick some of these to staging.

**Comment by MistakeNot4892** [comment]
Never mind, they don't apply and we're finishing staging soon anyway.

**Review by out-of-phaze — DISMISSED** [review]

**Review by out-of-phaze — DISMISSED** [review]

**Comment by comma** [comment]
Needs map repath thingie for gloves/color

**Review by out-of-phaze — APPROVED** [review]
No content changes since my review, so it should be ready to go in ~15 minutes.

**Pull request merged**
