### PR TITLE
Bottle/beaker/vial icon changes

### PR DESCRIPTION
**Pull request by comma**
Bottles now use new fancy sprites by Keekenox
Instead of different sprites you can now set color of lid and label when making a bottle in chemmaster.
All beakers were given shitty codersprites to fit in with new bottles
Under the hood they all now utilize bunch of overlays to properly support material colors and opacity without making things look like too much ass. Some bottles are now plastic to showcase that (hydroponic stuff mostly)
Also squashed bottle definitions a bunch, now they auto-name based on initial reagents unless overriden with custom label.
image

## Changelog
:cl:
tweak: Instead of selecting bottle sprite, you can now select lid and label color
rscadd: Sprites for bottles and beakers were changed
/:cl:

### CODE REVIEW

**Comment by quardbreak** [comment]
Would be nice if someone test this with big pharma modpack.

**Comment by MistakeNot4892** [comment]
Would like to know how this interacts with the big pharma modpack before approving. Code looks fine though.

**Comment by comma** [comment]
Yeah it totally doesn't interact with big pharma, need to hack something for that.

**Comment by comma** [comment]
TODO : handle_med_obfuscation

**Comment by MistakeNot4892** [comment]
https://github.com/comma/Nebula/pull/2/files

**Review by MistakeNot4892 — APPROVED** [review]

**Pull request merged**
