### PR TITLE
Fix a typo in a type path for the can_float proc for aquatic simple animals

### PR DESCRIPTION
**Pull request by PsyCommando**
## Description of changes

I was wondering why there was a /mob/living/aquatic type floating around in the mob types... So I corrected the path. Hopefully it refers to the right aquatic class since there's a few of them..

## Changelog

:cl:
tweak: Fishes can float now.
/:cl:

### CODE REVIEW

**Review by quardbreak — CHANGES_REQUESTED** [review]
Please add same override for `/mob/living/simple_animal/hostile/retaliate/aquatic` below since we have subtype under hostile type too.

**Comment by MistakeNot4892** [comment]
There's also `/mob/living/simple_animal/hostile/aquatic` if you don't mind adding a couple more.

**Comment by PsyCommando** [comment]
God all the aquatics XD
I sorta wonder if now that we got AI separated from the mob, if it wouldn't be easier to get rid of the friendly, hostile and retaliate subtypes?

**Comment by MistakeNot4892** [comment]
That's on the cards for when someone gets around to rewriting AI to run on datums instead of being hardcoded to the type.

**Review by MistakeNot4892 — APPROVED** [review]

**Comment by PsyCommando** [comment]
Might do that since I'm working on animal AI for ps13 anyways.

**Review by comma — APPROVED** [review]

**Pull request merged**
