### PR TITLE
Converting many grab attackby() blocks into grab_attack().

### PR DESCRIPTION
**Pull request by MistakeNot4892**
## Description of changes
Breaks various blocks out of attackby() into grab_attack().

## Why and what will this PR improve
Allows grab attack overrides to function properly without wonky proc flow like structure base grab interactions talking precedence over attackby().

## Authorship
Myself.

## Changelog
Nothing player-facing.

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
Depends on #4462 railing changes.

**Comment by MistakeNot4892** [comment]
All appears to be working.

**Review by out-of-phaze — DISMISSED** [review]
a little worried about the reversed arg order (user then item instead of item then user) causing issues down the line/when migrating legacy code, but it'll probably be fine. ~~it's something typemaker will hopefully be able to detect eventually, at least~~

**Comment by MistakeNot4892** [comment]
> a little worried about the reversed arg order (user then item instead of item then user) causing issues down the line/when migrating legacy code, but it'll probably be fine. ~it's something typemaker will hopefully be able to detect eventually, at least~

Easy enough to tweak it.

**Review by out-of-phaze — DISMISSED** [review]

**Review by out-of-phaze — APPROVED** [review]

**Pull request merged**
