### PR TITLE
Fix: you can't move yourself with a grab

### LINKED ISSUE #2412: Moving yourself with grab.
#### Description of issue

It's possible to move yourself by grabbing and then clicking to neighboring turf.

#### Difference between expected and actual behavior

It shouldn't be possible to move yourself with grab.

#### Steps to reproduce

1) Grab yourself
2) Click on neighboring turf with left mouse button

#### Length of time in which bug has been known to occur

4 month at least

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 90b889aef804d7847341155a73bec8eac346f60a - 7341155a73bec8eac346f60a - 
Game ID: ch0-c5GC

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

### PR DESCRIPTION
**Pull request by Gaxeer**
## Description of changes

Remove ability to move yourself with grab
fix https://github.com/NebulaSS13/Nebula/issues/2412

## Why and what will this PR improve

I suppose SS13 isn't a Fight Club, where Narrator could move himself with a grab :D
So, if you think so too, this should be restricted.

## Authorship

@Gaxeer  <-- Ye, that's me

## Changelog

:cl:
bugfix: disable ability to move yourself with grab
/:cl:

### CODE REVIEW

**Comment by afterthought2** [comment]
So I think I agree that this is an interaction which should be avoided, but will leave this open for a bit to see if others have different opinions.

**Review by MistakeNot4892 — DISMISSED** [review]

**Comment by MistakeNot4892** [comment]
I think this is probably something I actually removed when I redid grabs on Neb.

**Comment by MistakeNot4892** [comment]
Whoops, target staging please.

**Comment by Gaxeer** [comment]
> Whoops, target staging please.

Done

**Review by afterthought2 — APPROVED** [review]

**Pull request merged**
